"""Temporary code update

Revision ID: 456ee378c4fa
Revises: 57daad0a4fda
Create Date: 2024-11-20 04:13:09.608488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '456ee378c4fa'
down_revision: Union[str, None] = '57daad0a4fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temporary_codes', 'temp_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=6),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('temporary_codes', 'temp_code',
               existing_type=sa.String(length=6),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
