"""v7 - Roles updated

Revision ID: fdbfd9162d1c
Revises: edc947f2ce60
Create Date: 2024-11-16 03:58:35.842352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdbfd9162d1c'
down_revision: Union[str, None] = 'edc947f2ce60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
